version: '3.8'
services:
  nodejs-app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./nodejs:/app
    networks:
      - letaskono-network
  nextjs-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
    networks:
      - letaskono-network

networks:
  letaskono-network:
    driver: bridge